export const EXECUTION_MODES = [
  "assessment",
  "guided_questions",
  "structured_form",
  "checklist",
  "choice",
  "recommendation_selection",
  "research",
  "generator",
  "document_builder",
  "spreadsheet_builder",
  "image_generation",
  "upload_and_review",
  "conversation",
  "result_review",
];
