export const PROJECT_RESOURCE_TYPES = [
  "markdown",
  "text",
  "pdf",
  "word",
  "excel",
  "image",
  "checklist",
  "study_notes",
  "flashcards",
  "business_plan",
  "strategy",
  "spreadsheet",
  "timeline",
  "questionnaire",
  "test",
  "summary",
  "document",
];

export const PROJECT_RESOURCE_STRATEGIES = [
  "reuse_resource",
  "use_tool",
  "generate_resource",
  "web_then_generate",
  "project_brain",
];

export const PROJECT_RESOURCE_SELECT_COLUMNS = [
  "id",
  "project_id",
  "user_id",
  "step_id",
  "action_id",
  "result_id",
  "resource_type",
  "title",
  "preview",
  "content",
  "mime_type",
  "file_extension",
  "metadata",
  "source_strategy",
  "created_at",
  "updated_at",
].join(",");

export const RESOURCE_TYPE_HINTS = {
  financiar: "spreadsheet",
  buget: "spreadsheet",
  plan: "business_plan",
  marketing: "strategy",
  vocabular: "study_notes",
  flashcard: "flashcards",
  test: "test",
  checklist: "checklist",
  calendar: "timeline",
  analiza: "document",
  strategie: "strategy",
};
